# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1
image: Visual Studio 2017 Preview
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
before_build:
  - dotnet restore .\src\ZendeskApi_v2.sln
build:
  project: \src\ZendeskApi_v2.sln
  verbosity: detailed
test:
  assemblies: '.\test\**\bin\**\*test.dll'
artifacts:
- path: src\ZendeskApi_v2\bin\Release\ZendeskApi_v2.*.nupkg
  name: Package
deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: Environment
  name: PreRelease Nuget Feed
  on:
    branch: master
    APPVEYOR_REPO_TAG: false
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

install:
- ps: >-

    choco install gitversion.portable --pre --no-progress -y
    
    $output = gitversion
    
    $joined = $output -join "`n"
    
    $versionInfo = $joined | ConvertFrom-Json
    
    $versionInfo | % { foreach ($property in $_.PSObject.Properties) { Set-AppveyorBuildVariable -Name "GitVersion_$($property.Name)" -Value "$($_.PSObject.properties[$property.Name].Value)"    }}
    
    $script_versionNumber = "$($versionInfo.NuGetVersionV2).build.$($env:APPVEYOR_BUILD_ID)"
    
    Update-AppveyorBuild -Version $script_versionNumber
    
    $env:script_versionNumber = $script_versionNumber
    
    $env:APPVEYOR_PATCHING_VERSION = "$($versionInfo.AssemblySemVer)"

    Write-Host "Build version: " $script_versionNumber
    
    Write-Host "Assembly version: " $env:APPVEYOR_PATCHING_VERSION

    if($script_versionNumber.contains("-")) {
      $env:Is_Prerelease  = 'true'
    }
    else
    {
      $env:Is_Prerelease  = 'false'
    }
    Write-Host "Is the build Prerelease: " $env:Is_Prerelease