# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

install:
- ps: >-

    choco install gitversion.portable -pre -y
    
    $output = gitversion
    
    $joined = $output -join "`n"
    
    $versionInfo = $joined | ConvertFrom-Json
    
    $versionInfo | % { foreach ($property in $_.PSObject.Properties) { Set-AppveyorBuildVariable -Name "GitVersion_$($property.Name)" -Value "$($_.PSObject.properties[$property.Name].Value)"    }}
    
    $script_versionNumber = "$($versionInfo.NuGetVersionV2).build.$($env:APPVEYOR_BUILD_ID)"
    
    Update-AppveyorBuild -Version $script_versionNumber
    
    $env:script_versionNumber = $script_versionNumber
    
    $env:APPVEYOR_PATCHING_VERSION = "$($versionInfo.AssemblySemVer)"

    Write-Host "Build version: " $script_versionNumber
    
    Write-Host "Assembly version: " $env:APPVEYOR_PATCHING_VERSION

    if($script_versionNumber.contains("-")) {
      $env:Is_Prerelease  = 'true'
    }
    else
    {
      $env:Is_Prerelease  = 'false'
    }

    Write-Host "Is the build Prerelease: " $env:Is_Prerelease
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_PATCHING_VERSION)
  assembly_file_version: $(APPVEYOR_PATCHING_VERSION)
  assembly_informational_version: $(APPVEYOR_PATCHING_VERSION)
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-

    cd C:\projects\zendeskapi-v2\src

    nuget.exe restore
build:
  project: C:\projects\zendeskapi-v2\src\ZendeskApi_v2_vs2013.sln
  verbosity: minimal
#test: on
#test_script:
#- ps: nunit3-console C:\projects\zendeskapi-v2\src\Tests\bin\Release\Tests.dll --result=myresults.xml;format=AppVeyor --framework:net-4.5
test:
  assemblies: '**\*tests.dll'
artifacts:
- path: '\src\ZendeskApi_v2_Package\*.nupkg'
  name: Package
deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master
    Is_Prerelease: false
- provider: Environment
  name: PreRelease Nuget Feed
  on:
    branch: master
    Is_Prerelease: true
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: svWGYdd7ARGNOOqfnDWlXWdMPOzM2FKvHIv/IzvNDJiApoLxQzjDl2tmoKBzbvDu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false