next-version: 3.5.1 
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
build-metadata-padding: 0
legacy-semver-padding: 0

branches: {}

continuous-delivery-fallback-tag: alpha
commit-message-incrementing: Enabled